# Generated by Django 4.0.3 on 2022-03-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='prazo',
            field=models.DateTimeField(null=True),
        ),
    ]
