# Generated by Django 4.0.3 on 2022-03-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_alter_quest_prazo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tentativa',
            old_name='nota',
            new_name='pontos',
        ),
        migrations.AddField(
            model_name='alternativa',
            name='certa',
            field=models.BooleanField(default=0),
        ),
    ]
