# Generated by Django 4.0.3 on 2022-03-31 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0004_tentativa_respostas_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='aluno',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quests.aluno'),
            preserve_default=False,
        ),
    ]
