# Generated by Django 4.0.3 on 2022-03-31 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0005_resposta_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tentativa',
            name='respostas',
        ),
        migrations.CreateModel(
            name='RespostaQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.aluno')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.quest')),
            ],
        ),
        migrations.AddField(
            model_name='resposta',
            name='resposta_quest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quests.respostaquest'),
            preserve_default=False,
        ),
    ]
